// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping.proto

package org.cyverse.events.ping;

public final class PingMessages {
  private PingMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:de.events.ping.Ping)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 event_id = 1;</code>
     */
    int getEventId();

    /**
     * <code>optional string ping_to = 2;</code>
     */
    java.lang.String getPingTo();
    /**
     * <code>optional string ping_to = 2;</code>
     */
    com.google.protobuf.ByteString
        getPingToBytes();
  }
  /**
   * Protobuf type {@code de.events.ping.Ping}
   */
  public  static final class Ping extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:de.events.ping.Ping)
      PingOrBuilder {
    // Use Ping.newBuilder() to construct.
    private Ping(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Ping() {
      eventId_ = 0;
      pingTo_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Ping(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              eventId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              pingTo_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cyverse.events.ping.PingMessages.internal_static_de_events_ping_Ping_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cyverse.events.ping.PingMessages.internal_static_de_events_ping_Ping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cyverse.events.ping.PingMessages.Ping.class, org.cyverse.events.ping.PingMessages.Ping.Builder.class);
    }

    public static final int EVENT_ID_FIELD_NUMBER = 1;
    private int eventId_;
    /**
     * <code>optional int32 event_id = 1;</code>
     */
    public int getEventId() {
      return eventId_;
    }

    public static final int PING_TO_FIELD_NUMBER = 2;
    private volatile java.lang.Object pingTo_;
    /**
     * <code>optional string ping_to = 2;</code>
     */
    public java.lang.String getPingTo() {
      java.lang.Object ref = pingTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pingTo_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ping_to = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPingToBytes() {
      java.lang.Object ref = pingTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pingTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (eventId_ != 0) {
        output.writeInt32(1, eventId_);
      }
      if (!getPingToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pingTo_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (eventId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, eventId_);
      }
      if (!getPingToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pingTo_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.cyverse.events.ping.PingMessages.Ping)) {
        return super.equals(obj);
      }
      org.cyverse.events.ping.PingMessages.Ping other = (org.cyverse.events.ping.PingMessages.Ping) obj;

      boolean result = true;
      result = result && (getEventId()
          == other.getEventId());
      result = result && getPingTo()
          .equals(other.getPingTo());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + EVENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getEventId();
      hash = (37 * hash) + PING_TO_FIELD_NUMBER;
      hash = (53 * hash) + getPingTo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.cyverse.events.ping.PingMessages.Ping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cyverse.events.ping.PingMessages.Ping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cyverse.events.ping.PingMessages.Ping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cyverse.events.ping.PingMessages.Ping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cyverse.events.ping.PingMessages.Ping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cyverse.events.ping.PingMessages.Ping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cyverse.events.ping.PingMessages.Ping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.cyverse.events.ping.PingMessages.Ping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cyverse.events.ping.PingMessages.Ping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cyverse.events.ping.PingMessages.Ping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.cyverse.events.ping.PingMessages.Ping prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code de.events.ping.Ping}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:de.events.ping.Ping)
        org.cyverse.events.ping.PingMessages.PingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cyverse.events.ping.PingMessages.internal_static_de_events_ping_Ping_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cyverse.events.ping.PingMessages.internal_static_de_events_ping_Ping_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cyverse.events.ping.PingMessages.Ping.class, org.cyverse.events.ping.PingMessages.Ping.Builder.class);
      }

      // Construct using org.cyverse.events.ping.PingMessages.Ping.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        eventId_ = 0;

        pingTo_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cyverse.events.ping.PingMessages.internal_static_de_events_ping_Ping_descriptor;
      }

      public org.cyverse.events.ping.PingMessages.Ping getDefaultInstanceForType() {
        return org.cyverse.events.ping.PingMessages.Ping.getDefaultInstance();
      }

      public org.cyverse.events.ping.PingMessages.Ping build() {
        org.cyverse.events.ping.PingMessages.Ping result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cyverse.events.ping.PingMessages.Ping buildPartial() {
        org.cyverse.events.ping.PingMessages.Ping result = new org.cyverse.events.ping.PingMessages.Ping(this);
        result.eventId_ = eventId_;
        result.pingTo_ = pingTo_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cyverse.events.ping.PingMessages.Ping) {
          return mergeFrom((org.cyverse.events.ping.PingMessages.Ping)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cyverse.events.ping.PingMessages.Ping other) {
        if (other == org.cyverse.events.ping.PingMessages.Ping.getDefaultInstance()) return this;
        if (other.getEventId() != 0) {
          setEventId(other.getEventId());
        }
        if (!other.getPingTo().isEmpty()) {
          pingTo_ = other.pingTo_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cyverse.events.ping.PingMessages.Ping parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cyverse.events.ping.PingMessages.Ping) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int eventId_ ;
      /**
       * <code>optional int32 event_id = 1;</code>
       */
      public int getEventId() {
        return eventId_;
      }
      /**
       * <code>optional int32 event_id = 1;</code>
       */
      public Builder setEventId(int value) {
        
        eventId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 event_id = 1;</code>
       */
      public Builder clearEventId() {
        
        eventId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object pingTo_ = "";
      /**
       * <code>optional string ping_to = 2;</code>
       */
      public java.lang.String getPingTo() {
        java.lang.Object ref = pingTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pingTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ping_to = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPingToBytes() {
        java.lang.Object ref = pingTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pingTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ping_to = 2;</code>
       */
      public Builder setPingTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pingTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ping_to = 2;</code>
       */
      public Builder clearPingTo() {
        
        pingTo_ = getDefaultInstance().getPingTo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ping_to = 2;</code>
       */
      public Builder setPingToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pingTo_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:de.events.ping.Ping)
    }

    // @@protoc_insertion_point(class_scope:de.events.ping.Ping)
    private static final org.cyverse.events.ping.PingMessages.Ping DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.cyverse.events.ping.PingMessages.Ping();
    }

    public static org.cyverse.events.ping.PingMessages.Ping getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Ping>
        PARSER = new com.google.protobuf.AbstractParser<Ping>() {
      public Ping parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Ping(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Ping> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ping> getParserForType() {
      return PARSER;
    }

    public org.cyverse.events.ping.PingMessages.Ping getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PongOrBuilder extends
      // @@protoc_insertion_point(interface_extends:de.events.ping.Pong)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 event_id = 1;</code>
     */
    int getEventId();

    /**
     * <code>optional string pong_from = 2;</code>
     */
    java.lang.String getPongFrom();
    /**
     * <code>optional string pong_from = 2;</code>
     */
    com.google.protobuf.ByteString
        getPongFromBytes();
  }
  /**
   * Protobuf type {@code de.events.ping.Pong}
   */
  public  static final class Pong extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:de.events.ping.Pong)
      PongOrBuilder {
    // Use Pong.newBuilder() to construct.
    private Pong(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Pong() {
      eventId_ = 0;
      pongFrom_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Pong(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              eventId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              pongFrom_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cyverse.events.ping.PingMessages.internal_static_de_events_ping_Pong_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cyverse.events.ping.PingMessages.internal_static_de_events_ping_Pong_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cyverse.events.ping.PingMessages.Pong.class, org.cyverse.events.ping.PingMessages.Pong.Builder.class);
    }

    public static final int EVENT_ID_FIELD_NUMBER = 1;
    private int eventId_;
    /**
     * <code>optional int32 event_id = 1;</code>
     */
    public int getEventId() {
      return eventId_;
    }

    public static final int PONG_FROM_FIELD_NUMBER = 2;
    private volatile java.lang.Object pongFrom_;
    /**
     * <code>optional string pong_from = 2;</code>
     */
    public java.lang.String getPongFrom() {
      java.lang.Object ref = pongFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pongFrom_ = s;
        return s;
      }
    }
    /**
     * <code>optional string pong_from = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPongFromBytes() {
      java.lang.Object ref = pongFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pongFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (eventId_ != 0) {
        output.writeInt32(1, eventId_);
      }
      if (!getPongFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pongFrom_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (eventId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, eventId_);
      }
      if (!getPongFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pongFrom_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.cyverse.events.ping.PingMessages.Pong)) {
        return super.equals(obj);
      }
      org.cyverse.events.ping.PingMessages.Pong other = (org.cyverse.events.ping.PingMessages.Pong) obj;

      boolean result = true;
      result = result && (getEventId()
          == other.getEventId());
      result = result && getPongFrom()
          .equals(other.getPongFrom());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + EVENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getEventId();
      hash = (37 * hash) + PONG_FROM_FIELD_NUMBER;
      hash = (53 * hash) + getPongFrom().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.cyverse.events.ping.PingMessages.Pong parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cyverse.events.ping.PingMessages.Pong parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cyverse.events.ping.PingMessages.Pong parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cyverse.events.ping.PingMessages.Pong parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cyverse.events.ping.PingMessages.Pong parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cyverse.events.ping.PingMessages.Pong parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cyverse.events.ping.PingMessages.Pong parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.cyverse.events.ping.PingMessages.Pong parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cyverse.events.ping.PingMessages.Pong parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cyverse.events.ping.PingMessages.Pong parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.cyverse.events.ping.PingMessages.Pong prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code de.events.ping.Pong}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:de.events.ping.Pong)
        org.cyverse.events.ping.PingMessages.PongOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cyverse.events.ping.PingMessages.internal_static_de_events_ping_Pong_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cyverse.events.ping.PingMessages.internal_static_de_events_ping_Pong_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cyverse.events.ping.PingMessages.Pong.class, org.cyverse.events.ping.PingMessages.Pong.Builder.class);
      }

      // Construct using org.cyverse.events.ping.PingMessages.Pong.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        eventId_ = 0;

        pongFrom_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cyverse.events.ping.PingMessages.internal_static_de_events_ping_Pong_descriptor;
      }

      public org.cyverse.events.ping.PingMessages.Pong getDefaultInstanceForType() {
        return org.cyverse.events.ping.PingMessages.Pong.getDefaultInstance();
      }

      public org.cyverse.events.ping.PingMessages.Pong build() {
        org.cyverse.events.ping.PingMessages.Pong result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cyverse.events.ping.PingMessages.Pong buildPartial() {
        org.cyverse.events.ping.PingMessages.Pong result = new org.cyverse.events.ping.PingMessages.Pong(this);
        result.eventId_ = eventId_;
        result.pongFrom_ = pongFrom_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cyverse.events.ping.PingMessages.Pong) {
          return mergeFrom((org.cyverse.events.ping.PingMessages.Pong)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cyverse.events.ping.PingMessages.Pong other) {
        if (other == org.cyverse.events.ping.PingMessages.Pong.getDefaultInstance()) return this;
        if (other.getEventId() != 0) {
          setEventId(other.getEventId());
        }
        if (!other.getPongFrom().isEmpty()) {
          pongFrom_ = other.pongFrom_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cyverse.events.ping.PingMessages.Pong parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cyverse.events.ping.PingMessages.Pong) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int eventId_ ;
      /**
       * <code>optional int32 event_id = 1;</code>
       */
      public int getEventId() {
        return eventId_;
      }
      /**
       * <code>optional int32 event_id = 1;</code>
       */
      public Builder setEventId(int value) {
        
        eventId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 event_id = 1;</code>
       */
      public Builder clearEventId() {
        
        eventId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object pongFrom_ = "";
      /**
       * <code>optional string pong_from = 2;</code>
       */
      public java.lang.String getPongFrom() {
        java.lang.Object ref = pongFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pongFrom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pong_from = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPongFromBytes() {
        java.lang.Object ref = pongFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pongFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pong_from = 2;</code>
       */
      public Builder setPongFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pongFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pong_from = 2;</code>
       */
      public Builder clearPongFrom() {
        
        pongFrom_ = getDefaultInstance().getPongFrom();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pong_from = 2;</code>
       */
      public Builder setPongFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pongFrom_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:de.events.ping.Pong)
    }

    // @@protoc_insertion_point(class_scope:de.events.ping.Pong)
    private static final org.cyverse.events.ping.PingMessages.Pong DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.cyverse.events.ping.PingMessages.Pong();
    }

    public static org.cyverse.events.ping.PingMessages.Pong getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Pong>
        PARSER = new com.google.protobuf.AbstractParser<Pong>() {
      public Pong parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Pong(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Pong> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pong> getParserForType() {
      return PARSER;
    }

    public org.cyverse.events.ping.PingMessages.Pong getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_de_events_ping_Ping_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_de_events_ping_Ping_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_de_events_ping_Pong_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_de_events_ping_Pong_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nping.proto\022\016de.events.ping\")\n\004Ping\022\020\n\010" +
      "event_id\030\001 \001(\005\022\017\n\007ping_to\030\002 \001(\t\"+\n\004Pong\022" +
      "\020\n\010event_id\030\001 \001(\005\022\021\n\tpong_from\030\002 \001(\tB-\n\027" +
      "org.cyverse.events.pingB\014PingMessagesZ\004p" +
      "ingb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_de_events_ping_Ping_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_de_events_ping_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_de_events_ping_Ping_descriptor,
        new java.lang.String[] { "EventId", "PingTo", });
    internal_static_de_events_ping_Pong_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_de_events_ping_Pong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_de_events_ping_Pong_descriptor,
        new java.lang.String[] { "EventId", "PongFrom", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
